### ISSUE TITLE
Randomizer crashes/hangs on generation

### ISSUE THREAD

**Issue by Hobrok** [Vivelin/SMZ3Randomizer#257]
Having an issue where on version 8.0.1 the program stops responding when I have it generate a seed, though I don't get a log file out of it since I need to open task manager to close it. After downgrading to 7.0.3 it does manage to recognize it's encountered an error and spit out a log file at least.

```
2023-01-08T20:12:53.8084205-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Press Ctrl+C to shut down.
2023-01-08T20:12:53.8133333-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Hosting environment: Production
2023-01-08T20:12:53.8133606-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Content root path: E:\Programs\SMZ3 Cas Randomizer
2023-01-08T20:12:55.3163472-05:00	INFO	[Randomizer.App.Controls.SoloRomListPanel]	[0]	1 installed recognizer(s): Microsoft Speech Recognizer 8.0 for Windows (English - US)
2023-01-08T20:12:55.5905223-05:00	INFO	[Randomizer.App.Controls.MultiRomListPanel]	[0]	1 installed recognizer(s): Microsoft Speech Recognizer 8.0 for Windows (English - US)
2023-01-08T20:14:04.3107293-05:00	INFO	[Randomizer.SMZ3.Generation.GameHintService]	[0]	You can find the Plasma at Inner Maridia - the room in Maridia near the forgotten highway to Wrecked Ship.
2023-01-09T00:13:57.3739877-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Press Ctrl+C to shut down.
2023-01-09T00:13:57.3919803-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Hosting environment: Production
2023-01-09T00:13:57.3920361-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Content root path: E:\Programs\SMZ3 Cas Randomizer
2023-01-09T00:13:59.9385194-05:00	INFO	[Randomizer.App.RomListWindow]	[0]	1 installed recognizer(s): Microsoft Speech Recognizer 8.0 for Windows (English - US)
2023-01-09T00:14:12.7448765-05:00	CRIT	[Randomizer.App.App]	[0]	[CRASH] Uncaught DbUpdateException in Dispatcher: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'NOT NULL constraint failed: GeneratedRoms.Label'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Randomizer.Data.Services.TrackerStateService.CreateStateAsync(World world, GeneratedRom generatedRom) in D:\Source\SMZ3Randomizer\src\Randomizer.Data\Services\TrackerStateService.cs:line 59
   at Randomizer.App.RomGenerator.SaveSeedToDatabaseAsync(RandomizerOptions options, SeedData seed, String romPath, String spoilerPath) in D:\Source\SMZ3Randomizer\src\Randomizer.App\RomGenerator.cs:line 370
   at Randomizer.App.RomGenerator.GenerateRomInternalAsync(SeedData seed, RandomizerOptions options) in D:\Source\SMZ3Randomizer\src\Randomizer.App\RomGenerator.cs:line 185
   at Randomizer.App.RomGenerator.GenerateRandomRomAsync(RandomizerOptions options, Int32 attempts) in D:\Source\SMZ3Randomizer\src\Randomizer.App\RomGenerator.cs:line 101
   at Randomizer.App.GenerateRomWindow.GenerateRomButton_Click(Object sender, RoutedEventArgs e) in D:\Source\SMZ3Randomizer\src\Randomizer.App\Windows\GenerateRomWindow.xaml.cs:line 360
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

2023-01-09T00:18:40.3301589-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Press Ctrl+C to shut down.
2023-01-09T00:18:40.3335496-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Hosting environment: Production
2023-01-09T00:18:40.3335773-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Content root path: E:\Programs\SMZ3 Cas Randomizer
2023-01-09T00:18:41.5087453-05:00	INFO	[Randomizer.App.RomListWindow]	[0]	1 installed recognizer(s): Microsoft Speech Recognizer 8.0 for Windows (English - US)
2023-01-09T00:18:58.5879027-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application is shutting down...
2023-01-09T00:21:51.7194264-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Press Ctrl+C to shut down.
2023-01-09T00:21:51.7245127-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Hosting environment: Production
2023-01-09T00:21:51.7246098-05:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Content root path: E:\Programs\SMZ3 Cas Randomizer
2023-01-09T00:21:52.9058934-05:00	INFO	[Randomizer.App.RomListWindow]	[0]	1 installed recognizer(s): Microsoft Speech Recognizer 8.0 for Windows (English - US)
2023-01-09T00:21:58.8496467-05:00	CRIT	[Randomizer.App.App]	[0]	[CRASH] Uncaught DbUpdateException in Dispatcher: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'NOT NULL constraint failed: GeneratedRoms.Label'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Randomizer.Data.Services.TrackerStateService.CreateStateAsync(World world, GeneratedRom generatedRom) in D:\Source\SMZ3Randomizer\src\Randomizer.Data\Services\TrackerStateService.cs:line 59
   at Randomizer.App.RomGenerator.SaveSeedToDatabaseAsync(RandomizerOptions options, SeedData seed, String romPath, String spoilerPath) in D:\Source\SMZ3Randomizer\src\Randomizer.App\RomGenerator.cs:line 370
   at Randomizer.App.RomGenerator.GenerateRomInternalAsync(SeedData seed, RandomizerOptions options) in D:\Source\SMZ3Randomizer\src\Randomizer.App\RomGenerator.cs:line 185
   at Randomizer.App.RomGenerator.GenerateRandomRomAsync(RandomizerOptions options, Int32 attempts) in D:\Source\SMZ3Randomizer\src\Randomizer.App\RomGenerator.cs:line 101
   at Randomizer.App.RomListWindow.QuickPlayButton_Click(Object sender, RoutedEventArgs e) in D:\Source\SMZ3Randomizer\src\Randomizer.App\Windows\RomListWindow.xaml.cs:line 102
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by MattEqualsCoder** [comment]
Sorry to hear about the new version hanging for you!

Unfortunately I think due to the nullability updates with the .NET upgrade, the database got updated to require some fields to have values that makes the old versions incompatible with the current database, so downgrading to 7.0.3 isn't going to be possible like I had hoped it would be. We'll need to figure out what's going on with your 8.0.1 version.

Looking at your logs, it looks like it might have hung up on hint generation, but it's hard to say. I'm not seeing anything in the code that would make sense for it to hang up, but it's hard to say exactly due to current logging. I've added some additional logging into the next version that may give a better indication as to why it's hanging as well as give details that will hopefully allow me to reproduce on my end.

**Comment by MattEqualsCoder** [comment]
@Hobrok I uploaded a new version [here](https://github.com/Vivelin/SMZ3Randomizer/releases/tag/v8.0.2). While I doubt this fixes the original issue, I added logging that might help us pinpoint where the issue. Based on the logs above it does look like it was logging up to a certain point.

But, maybe this was a weird one off thing.

**Comment by Hobrok** [comment]
@MattEqualsCoder Yeah, it was hanging multiple times with 8.0.1, and I downloaded 8.0.2 and it still ends up hanging but it at least is generating a log file now. One other thing I've noticed is it has zero issues with the Generate Stats function, it'll do that function with zero issues though not sure if that's useful to know.
[smz3-cas-20230109.log](https://github.com/Vivelin/SMZ3Randomizer/files/10375853/smz3-cas-20230109.log)

**Comment by MattEqualsCoder** [comment]
@Hobrok Okay, cool. The logs ended up being helpful. I think this is a bug with generating seeds with 0 hints. Can you try testing with 1 or more hints? If that fixes it for you, then I'll put in a fix for the next version to fix selecting 0 hints. Sorry about the issue.

**Comment by Hobrok** [comment]
@MattEqualsCoder Okay, that got it to work. Thanks
